# -*- coding: utf-8 -*-
"""nlp_prob1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Cdkd5GP_MuhzdUAWX0-VjM5-YBCSbx3l
"""

# !pip install PyPDF2 gensim pdfplumber nltk matplotlib wordcloud scikit-learn

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')

# !pip install gensim

# !pip install pdfplumber

"""

Task 1: Dataset Preparation

"""

# importing libraries

import os
import re
import string
import PyPDF2
from collections import Counter
import matplotlib.pyplot as plt
from wordcloud import WordCloud
import nltk

nltk.download('punkt')

## file paths defining

pdf_files = [
    "2_Academic_Regulations_Final_03_09_2019.pdf",
    "Khamma-Ghani_Vol1_Issue1-2_Jan-June_2015.pdf",
    "Khamma-Ghani_Vol2_Issue2_July_Dec_2016_13May2017.pdf",
    "6_2024-04-17-661f605b54457-1713332315.pdf",
    "514efd70-4a12-4c48-92ef-f8b6f9d3666a.pdf",
    "Hazra,Ghosh.pdf"
]

def extract_text_from_pdf(file_path):
    """
    Extracts raw text from a PDF file page by page.
    Returns complete text as a single string.
    """
    text = ""

    with open(file_path, "rb") as file:
        reader = PyPDF2.PdfReader(file)

        for page in reader.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text


#removing non english text here

def keep_english_text(text):
    """
    Removes non-ASCII characters.
    This helps remove Hindi text and encoding artifacts.
    """
    return text.encode("ascii", errors="ignore").decode()


#removing boilerplates from text here

def remove_boilerplate(text):
    """
    Removes common formatting artifacts such as:
    - Page numbers
    - Headers
    - Repeated volume information
    """

    # Remove page numbers like "Page 1 of 6"
    text = re.sub(r'Page\s*\d+\s*of\s*\d+', ' ', text)

    # Remove standalone numbers
    text = re.sub(r'\b\d+\b', ' ', text)

    # Remove repeated phrases
    text = re.sub(r'IIT Jodhpur', ' ', text, flags=re.IGNORECASE)

    return text



def clean_text(text):
    """
    Performs final cleaning:
    - Lowercasing
    - Removing punctuation
    - Removing extra spaces
    """

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # Remove multiple spaces
    text = re.sub(r'\s+', ' ', text)

    return text

# noe building complete corpus

complete_text = ""

for pdf in pdf_files:
    print(f"Processing: {pdf}")
    raw_text = extract_text_from_pdf(pdf)
    english_text = keep_english_text(raw_text)
    no_boilerplate = remove_boilerplate(english_text)
    cleaned = clean_text(no_boilerplate)

    complete_text += cleaned + " "

# tokenization below

tokens = nltk.word_tokenize(complete_text)

# Remove very short tokens (noise)
tokens = [word for word in tokens if len(word) > 1]

from nltk.corpus import stopwords
nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

filtered_tokens = [word for word in tokens if word not in stop_words]

# data statistics

total_documents = len(pdf_files)
total_tokens = len(tokens)
vocab = set(tokens)
vocab_size = len(vocab)

print("\n DATASET STATISTICS")
print(f"Total Documents: {total_documents}")
print(f"Total Tokens: {total_tokens}")
print(f"Vocabulary Size: {vocab_size}")

 # saving the clean corpus now

with open("clean_corpus.txt", "w", encoding="utf-8") as f:
    f.write(" ".join(tokens))

print("\nClean corpus saved as 'clean_corpus.txt'")

# wordcloud generation
wordcloud = WordCloud(
    width=1000,
    height=500,
    background_color='white'
).generate(" ".join(tokens))

plt.figure(figsize=(12, 6))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis('off')
plt.title("Word Cloud of IIT Jodhpur Corpus")
plt.show()
# Get top 10 frequent words (after removing stopwords)
top10_words = Counter(filtered_tokens).most_common(10)

print("Top 10 Most Frequent Words:")

output = []

for word, freq in top10_words:
    output.append(f"{word}, {freq}")

print(", ".join(output))

"""

TASK 2:


"""
import re
import pdfplumber


complete_text = ""
#Preparing sentence-level corpus for Word2Vec training.
for pdf in pdf_files:
    with pdfplumber.open(pdf) as pdf_file:
        for page in pdf_file.pages:
            page_text = page.extract_text()
            if page_text:
                # keep punctuation here
                clean_ascii = page_text.encode("ascii", errors="ignore").decode()
                complete_text += clean_ascii + "\n"

# Now check punctuation exists
print("Does text contain period?", "." in complete_text)

# Split into sentences BEFORE cleaning punctuation
raw_sentences = re.split(r'[.!?]+\s+', complete_text)

print("Raw sentence count:", len(raw_sentences))

# Now clean each sentence
sentences = []

for sent in raw_sentences:
    sent = sent.lower()

    # Keep only alphabetic words
    tokens = re.findall(r'\b[a-zA-Z]{3,}\b', sent)

    if len(tokens) > 3:
        sentences.append(tokens)

print("Final usable sentences:", len(sentences))
print("Example:", sentences[0])

"""
Training CBOW Word2Vec model
"""

from gensim.models import Word2Vec

cbow_model = Word2Vec(
    sentences=sentences,
    vector_size=100,      # Embedding dimension
    window=5,             # Context window size
    min_count=2,          # Ignore rare words
    workers=4,
    sg=0,                 # 0 = CBOW
    negative=5,           # Negative samples
    epochs=10,
    compute_loss=True
)

print("CBOW model trained successfully.")
print("CBOW training loss:", cbow_model.get_latest_training_loss())
"""
Training Skip-gram with Negative Sampling
"""

skipgram_model = Word2Vec(
    sentences=sentences,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4,
    sg=1,          # 1 = Skip-gram
    negative=5,
    epochs=10,
    compute_loss=True

)

print("Skip-gram model trained successfully.")
print("Skip-gram training loss:", skipgram_model.get_latest_training_loss())
"""
Hyperparameter experimentation for both models.
"""

embedding_dims = [50, 100, 200]
window_sizes = [3, 5]
negative_samples = [5, 10]

experiment_results = []

print("Starting hyperparameter experiments...")

for dim in embedding_dims:
    for window in window_sizes:
        for neg in negative_samples:

            model = Word2Vec(
                sentences=sentences,
                vector_size=dim,
                window=window,
                min_count=2,
                sg=1,   # experimenting on Skip-gram
                negative=neg,
                epochs=5,
                compute_loss=True
            )

            loss = model.get_latest_training_loss()

            experiment_results.append({
                "Dimension": dim,
                "Window": window,
                "Negative Samples": neg,
                "Training Loss": loss
            })

print("Experiments completed.")

for res in experiment_results:
    print(res)
cbow_model.save("cbow_model.model")
skipgram_model.save("skipgram_model.model")

"""
TASK 3: Semantic analysis
"""

target_words = ["research", "student", "phd", "exam"]

for word in target_words:
    print(f"\n{word.upper()}")

    if word in skipgram_model.wv.key_to_index:

        print("Skip-gram:")
        print(skipgram_model.wv.most_similar(word, topn=5))

        print("CBOW:")
        print(cbow_model.wv.most_similar(word, topn=5))

    else:
        print(f"'{word}' not found in vocabulary")

# analogy1:
print("\n Analogy 1: student : semester :: research : ?")
print(skipgram_model.wv.most_similar(
    positive=["research", "semester"],
    negative=["student"],
    topn=5
))

# analogy2:
print("\n Analogy 2: course : credits :: project : ?")
print(skipgram_model.wv.most_similar(
    positive=["project", "credits"],
    negative=["course"],
    topn=5
))

# analogy3:
print("\n Analogy 3: student : grade :: research : ?")
print(skipgram_model.wv.most_similar(
    positive=["research", "grade"],
    negative=["student"],
    topn=5
))
vec = skipgram_model.wv['semester']
print("semester -", ", ".join(map(str, vec)))

"""
Task 4: visualization:

"""
selected_words = [
    "student", "students", "semester", "registration", "grade",
    "research", "project", "supervisor", "academic",
    "course", "credits", "degree", "engineering",
    "optimization", "data", "learning", "science"
]
for w in selected_words:
    print(w, w in skipgram_model.wv)
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import numpy as np

# Extract vectors
word_vectors = []
valid_words = []

for word in selected_words:
    if word in skipgram_model.wv:
        word_vectors.append(skipgram_model.wv[word])
        valid_words.append(word)

word_vectors = np.array(word_vectors)

# Apply PCA
pca = PCA(n_components=2)
reduced_vectors = pca.fit_transform(word_vectors)

# Plot
plt.figure(figsize=(10, 8))

for i, word in enumerate(valid_words):
    x = reduced_vectors[i, 0]
    y = reduced_vectors[i, 1]
    plt.scatter(x, y)
    plt.text(x + 0.01, y + 0.01, word)

plt.title("PCA Visualization - Skip-gram Embeddings")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid()
plt.show()


word_vectors = []
valid_words = []

for word in selected_words:
    if word in cbow_model.wv:
        word_vectors.append(cbow_model.wv[word])
        valid_words.append(word)

word_vectors = np.array(word_vectors)

pca = PCA(n_components=2)
reduced_vectors = pca.fit_transform(word_vectors)

plt.figure(figsize=(10, 8))

for i, word in enumerate(valid_words):
    x = reduced_vectors[i, 0]
    y = reduced_vectors[i, 1]
    plt.scatter(x, y)
    plt.text(x + 0.01, y + 0.01, word)

plt.title("PCA Visualization - CBOW Embeddings")
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.grid()
plt.show()