# -*- coding: utf-8 -*-
"""NLUA2Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9VvRwZD6FWv2rlJAnX6KSPTA1Wl3UOF
"""

# task 0:
## dataset prepration

# pip install torch 

import torch
"""
Load the dataset of names for character-level modeling
"""
# Read dataset
with open("TrainingName.txt", "r") as f:
    names = [line.strip().lower() for line in f if line.strip()]

print("Total names:", len(names))
print("Sample names:", names[:10])


"""
Build character vocabulary
"""

chars = sorted(list(set("".join(names))))

print("Unique characters:", chars)
print("Vocabulary size:", len(chars))


"""
Create character to index mappings
"""

char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

print("Example mapping:", list(char_to_idx.items())[:10])



"""
adding start and end token

"""


pad_token = "<pad>"
start_token = "^"
end_token = "$"

chars = sorted(list(set("".join(names))))
chars = [pad_token, start_token, end_token] + chars

char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(chars)

pad_idx = char_to_idx[pad_token]
print("Vocabulary size with tokens:", vocab_size)


"""
Convert names into training sequences
"""

import torch

inputs = []
targets = []

for name in names:

    seq = start_token + name + end_token

    input_seq = seq[:-1]
    target_seq = seq[1:]

    input_idx = [char_to_idx[ch] for ch in input_seq]
    target_idx = [char_to_idx[ch] for ch in target_seq]

    inputs.append(torch.tensor(input_idx))
    targets.append(torch.tensor(target_idx))

print("Example input indices:", inputs[0])
print("Example target indices:", targets[0])


"""
here we are padding seq for batch training

"""

from torch.nn.utils.rnn import pad_sequence


pad_token = "<pad>"
start_token = "^"
end_token = "$"

chars = sorted(list(set("".join(names))))
chars = [pad_token, start_token, end_token] + chars


char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(chars)

pad_idx = char_to_idx["<pad>"]

inputs_padded = pad_sequence(inputs, batch_first=True, padding_value=pad_idx)
targets_padded = pad_sequence(targets, batch_first=True, padding_value=pad_idx)
print("New vocab size:", vocab_size)

"""
now  dataloader

"""


from torch.utils.data import TensorDataset, DataLoader

dataset = TensorDataset(inputs_padded, targets_padded)

loader = DataLoader(dataset, batch_size=32, shuffle=True)

print("Dataset ready for training.")

# task 1:


## model 1: VANILLA RNN

import torch
import torch.nn as nn

class CharRNN(nn.Module):
    """
    Vanilla RNN model for character-level name generation.
    """

    def __init__(self, vocab_size, embed_size=32, hidden_size=64):
        super(CharRNN, self).__init__()

        self.embedding = nn.Embedding(vocab_size, embed_size, padding_idx=char_to_idx["<pad>"])
        self.rnn = nn.RNN(
            input_size=embed_size,
            hidden_size=hidden_size,
            batch_first=True
        )

        self.fc = nn.Linear(hidden_size, vocab_size)

    def forward(self, x):

        # Convert character indices → embeddings
        x = self.embedding(x)

        # Pass through RNN
        out, _ = self.rnn(x)

        # Predict next character
        out = self.fc(out)

        return out

# model defining
vocab_size = len(chars)

model = CharRNN(vocab_size)

criterion = nn.CrossEntropyLoss(ignore_index=pad_idx)
print(model)

## optimizer and loss function


optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.003
)

# training loop
epochs = 60

for epoch in range(epochs):

    total_loss = 0

    for x, y in loader:

        optimizer.zero_grad()

        outputs = model(x)

        # reshape for loss calculation
        outputs = outputs.view(-1, vocab_size)
        y = y.view(-1)

        mask = y != char_to_idx["<pad>"]

        outputs = outputs[mask]
        y = y[mask]

        loss = criterion(outputs, y)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss:.4f}")


# generate names from the model
import random

def generate_name(model, max_length=12):

    model.eval()

    sequence = [char_to_idx[start_token]]
    name = ""

    for _ in range(max_length):

        x = torch.tensor([sequence])

        output = model(x)

        probs = torch.softmax(output[0, -1], dim=0)

        next_idx = torch.multinomial(probs, 1).item()

        if idx_to_char[next_idx] == end_token:
            break

        if idx_to_char[next_idx] == "<pad>":
            continue

        sequence.append(next_idx)
        name += idx_to_char[next_idx]

    return name
for _ in range(10):
    print(generate_name(model))
print('total number of parameters:')
params=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(params)
rnn_model=model

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

# dataset
class NameDataset(Dataset):

    def __init__(self, names, char_to_idx, start_token, end_token):
        self.data = []

        for name in names:
            seq = start_token + name + end_token
            inp = seq[:-1]
            tgt = seq[1:]

            inp_idx = [char_to_idx[c] for c in inp]
            tgt_idx = [char_to_idx[c] for c in tgt]

            self.data.append((torch.tensor(inp_idx), torch.tensor(tgt_idx)))

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]


# collate function for padding
def collate_fn(batch):

    xs = [item[0] for item in batch]
    ys = [item[1] for item in batch]

    xs = nn.utils.rnn.pad_sequence(xs, batch_first=True, padding_value=pad_idx)
    ys = nn.utils.rnn.pad_sequence(ys, batch_first=True, padding_value=pad_idx)

    return xs, ys


dataset = NameDataset(names, char_to_idx, start_token, end_token)

loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    collate_fn=collate_fn
)

# BLSTM model
class BLSTMModel(nn.Module):

    def __init__(self, vocab_size):

        super().__init__()

        self.embedding = nn.Embedding(
            vocab_size,
            64,
            padding_idx=pad_idx
        )

        self.embedding = nn.Embedding(vocab_size, 64, padding_idx=pad_idx)

        self.lstm = nn.LSTM(
           64,
          128,
          num_layers=2,
          batch_first=True,
          bidirectional=True
          )

        self.fc = nn.Linear(256, vocab_size)
        self.fc = nn.Linear(256, vocab_size)

    def forward(self, x):

        x = self.embedding(x)

        out, _ = self.lstm(x)

        out = self.fc(out)

        return out


model = BLSTMModel(vocab_size)

# training
criterion = nn.CrossEntropyLoss(ignore_index=pad_idx)

optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 60

for epoch in range(epochs):

    total_loss = 0

    for x, y in loader:

        optimizer.zero_grad()

        out = model(x)

        out = out.reshape(-1, vocab_size)
        y = y.reshape(-1)

        loss = criterion(out, y)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(model.parameters(), 5)

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss:.3f}")

def generate_name(model, max_len=12):

    model.eval()

    seq = [char_to_idx[start_token]]

    name = ""

    for _ in range(max_len):

        x = torch.tensor([seq])

        out = model(x)

        probs = torch.softmax(out[0, -1], dim=0)

        # prevent start token and pad token
        probs[char_to_idx[start_token]] = 0
        probs[pad_idx] = 0

        # prevent immediate end token
        if len(seq) < 3:
          probs[char_to_idx[end_token]] = 0

        probs[pad_idx] = 0
        probs[char_to_idx[start_token]] = 0

        next_idx = torch.multinomial(probs, 1).item()

        if next_idx == char_to_idx[end_token]:
            break

        seq.append(next_idx)

        name += idx_to_char[next_idx]

    return name
for _ in range(10):
    print(generate_name(model))

print('total number of parameters:')
params=sum(p.numel() for p in model.parameters() if p.requires_grad)
print(params)
blstm_model=model

# task 1: model 3- rnn with attention

import torch
import torch.nn as nn

# attention RNN model
class AttentionRNN(nn.Module):

    def __init__(self, vocab_size, embed_size=64, hidden_size=128):
        super().__init__()

        self.embedding = nn.Embedding(vocab_size, embed_size, padding_idx=pad_idx)

        self.rnn = nn.GRU(
            embed_size,
            hidden_size,
            num_layers=2,
            batch_first=True
        )

        # Attention layer
        self.attn = nn.Linear(hidden_size, hidden_size)

        # Final prediction layer
        self.fc = nn.Linear(hidden_size * 2, vocab_size)

    def forward(self, x):

        emb = self.embedding(x)

        outputs, hidden = self.rnn(emb)

        # Compute attention weights
        attn_scores = torch.bmm(
            outputs,
            outputs.transpose(1, 2)
        )

        attn_weights = torch.softmax(attn_scores, dim=-1)

        # Compute context vector
        context = torch.bmm(attn_weights, outputs)

        # Concatenate context and outputs
        combined = torch.cat((outputs, context), dim=2)

        out = self.fc(combined)

        return out


# model defining
attn_model = AttentionRNN(vocab_size)

print(attn_model)


# training:
criterion = nn.CrossEntropyLoss(ignore_index=pad_idx)

optimizer = torch.optim.Adam(attn_model.parameters(), lr=0.001)

epochs = 50

for epoch in range(epochs):

    total_loss = 0

    for x, y in loader:

        optimizer.zero_grad()

        out = attn_model(x)

        out = out.reshape(-1, vocab_size)
        y = y.reshape(-1)

        loss = criterion(out, y)

        loss.backward()

        torch.nn.utils.clip_grad_norm_(attn_model.parameters(), 5)

        optimizer.step()

        total_loss += loss.item()

    print(f"Epoch {epoch+1} Loss: {total_loss:.3f}")

def generate_name_attention(model, max_len=12):

    model.eval()

    seq = [char_to_idx[start_token]]

    name = ""

    for _ in range(max_len):

        x = torch.tensor([seq])

        out = model(x)

        temperature = 0.7

        probs = torch.softmax(out[0, -1] / temperature, dim=0)

        probs[pad_idx] = 0
        probs[char_to_idx[start_token]] = 0

        if len(seq) < 3:
            probs[char_to_idx[end_token]] = 0

        next_idx = torch.multinomial(probs, 1).item()

        if next_idx == char_to_idx[end_token]:
            break

        seq.append(next_idx)

        name += idx_to_char[next_idx]

    return name

for _ in range(10):
    print(generate_name_attention(attn_model))

print('total number of parameters:')
params = sum(p.numel() for p in attn_model.parameters() if p.requires_grad)
print( params)
attn_model=attn_model

# task 2 : Quantitive analysis


NUM_GENERATED = 200

# name generation
def generate_names(model, num_names=NUM_GENERATED):

    generated = []

    for _ in range(num_names):

        name = generate_name(model)

        if len(name) > 0:
            generated.append(name)

    return generated


print("Generating names from models\n")

rnn_generated = generate_names(rnn_model)
blstm_generated = generate_names(blstm_model)
attn_generated = generate_names(attn_model)


#  Novelty Rate

def compute_novelty(generated_names, training_names):

    training_set = set(training_names)

    new_names = []

    for name in generated_names:

        if name not in training_set:
            new_names.append(name)

    novelty = len(new_names) / len(generated_names)

    return novelty


# Diversity

def compute_diversity(generated_names):

    unique_names = set(generated_names)

    diversity = len(unique_names) / len(generated_names)

    return diversity


# compute metrics
novelty_rnn = compute_novelty(rnn_generated, names)
novelty_blstm = compute_novelty(blstm_generated, names)
novelty_attn = compute_novelty(attn_generated, names)

diversity_rnn = compute_diversity(rnn_generated)
diversity_blstm = compute_diversity(blstm_generated)
diversity_attn = compute_diversity(attn_generated)


# results printing

print("\nResults are as follows:\n")

print("Vanilla RNN")
print("Novelty:", round(novelty_rnn,3))
print("Diversity:", round(diversity_rnn,3))
print()

print("Bidirectional LSTM")
print("Novelty:", round(novelty_blstm,3))
print("Diversity:", round(diversity_blstm,3))
print()

print("Attention RNN")
print("Novelty:", round(novelty_attn,3))
print("Diversity:", round(diversity_attn,3))



print("\nSample Names (RNN):")
print(rnn_generated[:10])

print("\nSample Names (BLSTM):")
print(blstm_generated[:10])

print("\nSample Names (Attention):")
print(attn_generated[:10])

# task 3: Qualitative analysis


NUM_SAMPLES = 100

# generating names

def generate_sample_names(model, num_samples=NUM_SAMPLES):

    generated = []

    for _ in range(num_samples):

        name = generate_name(model)

        if len(name) > 0:
            generated.append(name)

    return generated


print("Generating names for qualitative analysis...\n")

rnn_samples = generate_sample_names(rnn_model)
blstm_samples = generate_sample_names(blstm_model)
attn_samples = generate_sample_names(attn_model)


print("\nSAMPLE GENERATED NAMES \n")

print("Vanilla RNN:")
print(rnn_samples[:20])

print("\nBidirectional LSTM:")
print(blstm_samples[:20])

print("\nAttention RNN:")
print(attn_samples[:20])

# failure modes

def analyze_failures(generated_names):

    very_short = []
    repeated_chars = []
    strange_patterns = []

    for name in generated_names:

        # very short names
        if len(name) <= 2:
            very_short.append(name)

        # repeated characters
        if len(set(name)) < len(name) / 2:
            repeated_chars.append(name)

        # unusual character combinations
        if any(char not in "abcdefghijklmnopqrstuvwxyz" for char in name):
            strange_patterns.append(name)

    return very_short, repeated_chars, strange_patterns


# failure cases model wise :
rnn_fail = analyze_failures(rnn_samples)
blstm_fail = analyze_failures(blstm_samples)
attn_fail = analyze_failures(attn_samples)


# now printing the failures  model wise :
def print_analysis(model_name, samples, failures):

    short_names, repeated, strange = failures

    print(f"\n {model_name} ANALYSIS ")

    print("\nTotal generated:", len(samples))

    print("\nVery short names:", len(short_names))
    print(short_names[:10])

    print("\nRepeated character patterns:", len(repeated))
    print(repeated[:10])

    print("\nStrange patterns:", len(strange))
    print(strange[:10])


print_analysis("Vanilla RNN", rnn_samples, rnn_fail)
print_analysis("BLSTM", blstm_samples, blstm_fail)
print_analysis("Attention RNN", attn_samples, attn_fail)


# length distribution model wise:

def length_distribution(generated_names):

    lengths = [len(name) for name in generated_names]

    avg_length = sum(lengths) / len(lengths)

    return avg_length, min(lengths), max(lengths)


rnn_len = length_distribution(rnn_samples)
blstm_len = length_distribution(blstm_samples)
attn_len = length_distribution(attn_samples)


print("\nNAME LENGTH ANALYSIS ")

print("RNN -> Avg:", round(rnn_len[0],2), " Min:", rnn_len[1], " Max:", rnn_len[2])
print("BLSTM -> Avg:", round(blstm_len[0],2), " Min:", blstm_len[1], " Max:", blstm_len[2])
print("Attention -> Avg:", round(attn_len[0],2), " Min:", attn_len[1], " Max:", attn_len[2])